### ISSUE TITLE
Why cant i see hentai stuff on the app even when 18+ enabled with account? 

### ISSUE THREAD

**Issue by mananhiteshkataria** [AniTrend/anitrend-app#117]
## Additional Context
Cannot see any hentai related content on app 

I am currently using...

Samsung galaxy s9 +
Android 9.0

**Comment by wax911** [comment]
**[FAQ](https://anitrend.gitbook.io/project/faq)**

Please always use the provided templates for creating issues, and read the community guidelines before creating a new issue.

**Duplication of duplication of #92**
