### ISSUE TITLE
Unable to provide information regarding error!

### ISSUE THREAD

**Issue by Tensai-Otaku** [AniTrend/anitrend-app#320]
Today when Anilist was going under some problem. After it finally got solved. Now I cannot access anything on the Anitrend app and are constantly bombarded with this message. This is the only thing that comes.

**Comment by wax911** [comment]
Thanks for the issue sub-mission @Tensai-Otaku in future please take a moment to review our [**community guidelines**](https://github.com/AniTrend/anitrend-app/blob/master/CONTRIBUTING.md) and use the provided issue templates. 

Issues related to the side such as these which are out of our control cannot be resolved by us
