### ISSUE TITLE
"Anime Roles" tab for a Voice Actor (staff) shows instances of Anime Production Roles instead of all instances of anime that they have been in

### ISSUE THREAD

**Issue by doongs** [AniTrend/anitrend-app#327]
# AniTrend Issue Guidelines

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/AniTrend/anitrend-app/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**You may find an answer in already closed issues**:
https://github.com/AniTrend/anitrend-app/issues?q=is%3Aissue+is%3Aclosed

## Description Of Bug

**Anime Roles** tab for a Voice Actor (staff) shows instances of Anime Production Roles instead of all instances of anime that they have been in

**Steps To Reproduce**
1. Search for character Ayane Sakura
2. Click on **Anime Roles** tab

## Expected Behaviour

Missing many shows such as Your Lie in April and Oregairu. This tab is currently only showing the anime which Ayane Sakura has sung the OP or ED for (production role)

## Screenshots/Videos

![Screenshot_20201023-014601](https://user-images.githubusercontent.com/61425162/96960934-8c547e00-14d1-11eb-869a-6ca7091bd3e7.png)

Anime Roles Tab:
![Screenshot_20201023-014607](https://user-images.githubusercontent.com/61425162/96960940-8eb6d800-14d1-11eb-9197-e2eb8e7423b0.png)

![Screenshot_20201023-014610](https://user-images.githubusercontent.com/61425162/96960944-91b1c880-14d1-11eb-81e7-800453366ca2.png)

## Additional Context

If you're using the AniList GraphQL API:
I suspect the issue is that you are using the staffMedia field within the API, and that field returns media that the staff member had a production role in such as Theme Song Performance, Episode Director, Composer, or something else

Instead use Staff.characters.nodes.media.nodes (not sure if that query is 100% correct, but that's the idea)

**Comment by wax911** [comment]
Thank you for submitting an bug issue @doongs I will admit, this is something I had never noticed. Also your assumption is spot on, I am using `staffMedia` for [staff](https://github.com/AniTrend/anitrend-app/blob/develop/app/src/main/assets/graphql/queries/staff/detail/StaffMedia.graphql). I will probably resolve this in **v2.0** since I'm dedicating all my efforts to that instead. I will leave this open in this repo in-case some of the devs want to take a crack at it.

> Kindly please use the provided issue templates in future, I have edited your question to follow the issue guidelines :smiley_cat:
