### ISSUE TITLE
Quality of life

### ISSUE THREAD

**Issue by thatblackartist** [AniTrend/anitrend-app#354]
-Discover anime having an "all" tab for that year rather than in section of seasons. While also the option of choosing a range of years.
-Alphabetical "tags" sorting
-recommedations tab

**Comment by wax911** [comment]
Thanks for the suggestion, all the above requests were moved to **v2.0** and in future please use [contributing guidelines](https://github.com/AniTrend/anitrend-app/blob/develop/CONTRIBUTING.md) and the issue templates provided:

![image](https://user-images.githubusercontent.com/7859175/103073685-b4935280-45d0-11eb-89aa-e5500d2be546.png)

Example of a good issue: https://github.com/AniTrend/anitrend-app/issues/113

> As seen in the screenshot below:
> ![image](https://user-images.githubusercontent.com/7859175/103073504-67af7c00-45d0-11eb-8da4-c1297aa7af61.png)
