### ISSUE TITLE
Profile and Banner doesn't update

### ISSUE THREAD

**Issue by lrnzdc3696** [AniTrend/anitrend-app#405]
## Feature Information
I have been waiting for the update on this but no one seems to know.
When I edit my profile picture on the website, my profile on the app stays the same and doesn't change unless I reinstall/clear data the app

## Solution Information
Maybe let us have a button where we can fully update our data including profile pictures and other things

## Additional context
Profile on the app
![Screenshot_2021-05-05-23-48-38-05](https://user-images.githubusercontent.com/77531972/117160871-70c11d00-adfc-11eb-86b1-b091dce75e04.jpg)

Profile on the website
![Screenshot_2021-05-05-23-49-30-96](https://user-images.githubusercontent.com/77531972/117161091-9d753480-adfc-11eb-9878-eccaad732d6f.jpg)
https://anilist.co/user/WeMayNeverKnow/

**Comment by wax911** [comment]
Thank you for the bug report, I like the suggestion and will see how to best implement that.
