### ISSUE TITLE
Settings Crash

### ISSUE THREAD

**Issue by wax911** [AniTrend/anitrend-app#48]
__Caused by java.lang.SecurityException__
`
Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media/17116 from pid=6115, uid=10162 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
com.mxt.anitrend.view.activity.base.SettingsActivity.lambda$static$0$SettingsActivity`

**Comment by youssefhabri** [comment]
I think catching the error and preventing a crashing would be better :thinking: (maybe even alert the user to setup the permission).

**Comment by wax911** [comment]
True, well this crash was just for one user and after reaching out to the person I leant that the person had set a notification message from their SD Card the went into the application permissions and revoked all read/write access :laughing:
