### ISSUE TITLE
Cannot Connect to Anilist

### ISSUE THREAD

**Issue by Stiffpixels** [AniTrend/anitrend-app#504]
## Description Of Bug
Whenever opening ani trend app it shows a popup message from top in orange color saying-
 **"Could Not Complete Request Successfully"** 
null of null requests remaining, please retry after n seconds (maximum 60 seconds).
This issue persists on all pages including profile page, discover manga, etc

**Steps To Reproduce**
1. Open 

## Expected Behaviour

It should be able to open normally, and also i noticed something similar when you are trying to access any adult 18+ anime or manga before this issue occured.

## Screenshots/Videos

![Screenshot_2022-11-12-11-35-52-662_com.mxt.anitrend.jpg](https://user-images.githubusercontent.com/32983571/201460316-28fef3de-20a1-4651-8bd1-ba49600ef5e0.jpg)

## Device & Build Information

* OS Version: android 11 (Miui 12.5)
* App Version: 1.9.11 (beta)
* Phone Model: redmi note 7s
* Phone Brand: Xiaomi

Donwload Source:
- [x] Playstore
- [ ] Github
- [ ] Other (specify)

## Additional Context

I have not yet tested with other phones but even after clearing the cache and data it keeps happening.

**Comment by wax911** [comment]
Can confirm this is also happening on my device too, so far it seems like this is only affecting 3rd party clients

**Comment by Stiffpixels** [comment]
> Can confirm this is also happening on my device too, so far it seems like this is only affecting 3rd party clients

By 3rd party clients you mean non-stock os android phones?

**Comment by luk1337** [comment]
It could be cloudflare related. Does it fix itself if you open anilist in web browser and then go back to app?

**Comment by Stiffpixels** [comment]
> It could be cloudflare related. Does it fix itself if you open anilist in web browser and then go back to app?

I just tried it and no it does'nt fix it. Its still there.

**Comment by luk1337** [comment]
I looked into it a little bit, and it seems like this is a typical rate limit except for some reason "X-RateLimit-Limit", "X-RateLimit-Remaining" headers are no longer present.

**Comment by youssefhabri** [comment]
AniList are having server hardware issues, and so the API is not fully working as intended. It might work, or it might not, and add to that the Cloudflare Burst Limiter which will be getting triggered more often now, and you get the current situation.

Nothing we can do on our end. We'll just have to wait for them to solve their server hardware issues

**Comment by Stiffpixels** [comment]
> AniList are having server hardware issues, and so the API is not fully working as intended. It might work, or it might not, and add to that the Cloudflare Burst Limiter which will be getting triggered more often now, and you get the current situation.
> 
> Nothing we can do on our end. We'll just have to wait for them to solve their server hardware issues.
> 
> The announcement from AniList's Discord server:
> ![image](https://user-images.githubusercontent.com/1578005/201468806-8f95c2db-7711-4d3b-8a51-1d707d7e9bfd.png)

Just saw that on discord, Thanks for letting me know. Lets wait and see if it gets fixed then.

**Comment by Stiffpixels** [comment]
Seems like the issue has been resolved, i tried it and anilist api is working again.
