### ISSUE TITLE
Refactor android-build.yaml workflow

### ISSUE THREAD

**Issue by wax911** [AniTrend/anitrend-app#518]
# AniTrend Issue Guidelines

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/AniTrend/anitrend-app/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**You may find an answer in already closed issues**:
https://github.com/AniTrend/anitrend-app/issues?q=is%3Aissue+is%3Aclosed

## Feature Information 

This change removes the `test` job in the `android-build.yaml` which makes the runner run longer

## Solution Information

Since we can have required steps, we could make `android-test.yaml` a requirement prior to building the release files. Perhaps we could consider using https://github.com/marketplace/actions/wait-on-check

## Additional context
**TBA**

**Comment by taichikuji** [comment]
Everything looks good to me! Amazing stuff as always.
