### ISSUE TITLE
Media Scrolling on Feeds & Profiles

### ISSUE THREAD

**Issue by lionirdeadman** [AniTrend/anitrend-app#54]
Scrolling through media currently results in inaccurate numbering and could confuse the user.

**Comment by wax911** [comment]
I don't understand this issue? Which media are you talking about and on what Activity is this on, please go over your question again

**Comment by lionirdeadman** [comment]
On all activities, when you go through images, it counts improperly. You said it was to remember where the user was.

To reproduce : 
1. Go to any timeline
2. Look through the images
3. Next time you see images, they will not be numbered properly. (ex. 6/2, 4/3, etc.)

**Comment by wax911** [comment]
I see, thanks sadly there is no real counter, it's just a scrolling view which measures the width of each child / total width of all the children to give the illusion that the images are paginated. I've tried one fix but that results in hard resetting the position when the parent activity is resumed and all views have to be re-rendered :thinking:
