### ISSUE TITLE
Status Feeds Tab in Navigation Drawer Crashing Android 9.0

### ISSUE THREAD

**Issue by jalalmostafa** [AniTrend/anitrend-app#69]
## Issue Type

- [x] Bug

## Current Behavior

***Status Feeds*** tab in navigation drawer is crashing the application on Android 9

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. You should have Android 9
2. Press ***Status Feeds*** in navigation drawer

### Context

* OS Version: Android 9.0
* Phone Model: Pixel 2
* Phone Brand: Google

**Comment by wax911** [comment]
Thanks for the issue, I have not test with the latest android Pie yet, will check it out and see what we can do about it before the next release goes live
