### ISSUE TITLE
Java Compilation Error: "error: self-reference in initializer"

### ISSUE THREAD

**Issue by jalalmostafa** [AniTrend/anitrend-app#77]
I am trying to build the project so that I can debug #69 but no success. The build process fails on two compilation errors that are both "error: self-reference in initializer" in `RequestHandler` and `WebFactory`

![image](https://user-images.githubusercontent.com/3834578/44061902-e86064c0-9f62-11e8-832d-fb859f34756c.png)

Note that I am using:
- Android Studio 3.1.4
- Java SDK that is embedded in Android Studio
- Gradle 4.4 (embedded in Android Studio)

I suggest constructing a build instruction page for this project. The project is getting so big and the configuration needed to successfully launch the project is not minor either.

**Comment by TrickRoom** [comment]
Try cloning from Git GUI/command line/anything but Android Studio and then:

1. Move google-services.json from app/.travis-ci to the app/ directory
2. Move secrets from the aforementioned folder to the root direcotry of AniTrend and rename it to secrets.properties.

There is also documentation written here: [Link](https://anitrend.gitbook.io/project/)

**Comment by wax911** [comment]
Hi @jalalmostafa the issue #69 was already fixed in one of the commits that referenced the issue (just needs more testing) If you're interested in testing consider joining the discord server for anitrend (you can find the entry in __veritcal dots -> Extras -> Discord__

**Comment by jalalmostafa** [comment]
@TrickRoom thanks. It solved the issue. BTW, at first, I cloned using Github for Windows.

@wax911 I would be pleased to help!
