### ISSUE TITLE
Different list styles

### ISSUE THREAD

**Issue by w4tchdoge** [AniTrend/anitrend-app#89]
I'd like a list style similar to [the expanded list style](https://i.imgur.com/2s6wC5D.png) that AniList offers, making it far easier to scroll through than the [current list style](https://i.imgur.com/1CPXosS.png). Any input on whether this is possible or not is much appreciated.

**Comment by wax911** [comment]
Hi @w4tchdoge sorry for the late reply, it is possible to do but I can't give you an estimation on when this would be done as We've got a couple things on the current road map that need to be done

**Comment by w4tchdoge** [comment]
@wax911 Got it, thanks for the input.
